openapi: 3.0.3
info:
  title: Reference navigation example
  version: 1.0.0
paths:
  /pets:
    get:
      responses:
        '200':
          description: A pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
        owner:
          $ref: './models.json#/Owner'
